### ISSUE TITLE
能左右上下一起滑动吗？类似彩票统计那种效果？

### ISSUE THREAD

**Issue by zhuzhutai** [zhouchaoyuan/excelPanel#18]
随便一个彩票软件都有走势那种效果，如何实现呢

**Comment by zhouchaoyuan** [comment]
其实你这个问题我考虑过，但是彩票软件的都是嵌套一个网页，目前还没见过原生的。用原生来实现还是比较难的

**Comment by anpoz** [comment]
要想实现那种效果，需要继承recyclerview，修改onInterceptTouchEvent的实现逻辑才行，因为RecyclerView 并没有判断用户拖动的角度， 只是用来判断拖动的距离是否大于滚动的最小尺寸。 @zhuzhutai

**Comment by zhouchaoyuan** [comment]
感觉这是个挺不错的方法

**Comment by zhuzhutai** [comment]
偶然又翻到几年前的issues
那些年的需求早已实现...
开源真好
