### ISSUE TITLE
how to access scroll event and detect up down scroll ?

### ISSUE THREAD

**Issue by powerofdjy** [zhouchaoyuan/excelPanel#38]
Can you please tell how to access excelpanel's scroll event and detect up or down scrolling

**Comment by zhouchaoyuan** [comment]
try to use  
```java
compile 'cn.zhouchaoyuan:excelpanel:1.0.5'
///.....
        excelPanel.addOnScrollListener(new ExcelPanel.OnScrollListener() {
            @Override
            public void onScrolled(ExcelPanel excelPanel, int dx, int dy) {
                super.onScrolled(excelPanel, dx, dy);
            }
        });
```

**Comment by powerofdjy** [comment]
> try to use
> 
> ```java
> compile 'cn.zhouchaoyuan:excelpanel:1.0.5'
> ///.....
>         excelPanel.addOnScrollListener(new ExcelPanel.OnScrollListener() {
>             @Override
>             public void onScrolled(ExcelPanel excelPanel, int dx, int dy) {
>                 super.onScrolled(excelPanel, dx, dy);
>             }
>         });
> ```



> try to use
> 
> ```java
> compile 'cn.zhouchaoyuan:excelpanel:1.0.5'
> ///.....
>         excelPanel.addOnScrollListener(new ExcelPanel.OnScrollListener() {
>             @Override
>             public void onScrolled(ExcelPanel excelPanel, int dx, int dy) {
>                 super.onScrolled(excelPanel, dx, dy);
>             }
>         });
> ```

Thank you.. it works
