### ISSUE TITLE
左边Item的View必须是指定宽高的吗？

### ISSUE THREAD

**Issue by Yunme** [zhouchaoyuan/excelPanel#4]
如果左边Item的View是`wrap_content`或者`match_parent`，那么垂直方向的滑动就会变成单个`RecyclerView`在滑动。

**Comment by zhouchaoyuan** [comment]
发现这个问题了，目前暂时做不到wrap_content，需要指定一个高度

**Comment by Pannarrow** [comment]
Paint paint = new Paint();
paint.setTextSize(textsize);
float maxLeftWidth = paint.measureText(maxLeftStr) + paddingleft + paddingright;
View majorView = excelView.getChildAt(0);
if (majorView instanceof RecyclerView) {
      FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams)majorView.getLayoutParams();
      layoutParams.leftMargin = (int) maxLeftWidth;
      majorView.setLayoutParams(layoutParams);
}

View topView = excelView.getChildAt(1);
if (topView instanceof RecyclerView) {
      FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams)topView.getLayoutParams();
      layoutParams.leftMargin = (int) maxLeftWidth;
      topView.setLayoutParams(layoutParams);
}

View leftView = excelView.getChildAt(2);
if (leftView instanceof RecyclerView) {
     ViewGroup.LayoutParams layoutParams = leftView.getLayoutParams();
      layoutParams.width = (int)maxLeftWidth;
     leftView.setLayoutParams(layoutParams);
}
