### ISSUE TITLE
SQLite and history question

### ISSUE THREAD

**Issue by hassanrana** [zhouchaoyuan/excelPanel#42]
Hi,Can you please tell me how to stick to the future data only and not load any history data.My requirement is to get data from sqlite and show employee one month data here.Thank you in advance

**Comment by zhouchaoyuan** [comment]
Below is some sample codes from readme.
```java
    adapter = new CustomAdapter(this, blockListener);
    adapter.enableHeader();//load history, you can also call disableHeader()----default
```

do not call adapter.enableHeader();
I think this may help you.
